# We are using sudo with the --login flag to load
# the '~/.profile' with the expanded $PATH that is
# required to resolve the 'iptables' binary location.
- name: Execute the application deploy script.
  become: yes
  become_flags: --login
  command: /bin/bash ./deploy.bash
  args:
    chdir: /home/vagrant/application/
