- name: Copy the configuration file to '~/.profile'.
  copy:
    src: .profile
    dest: ~/.profile
    mode: 0644
  tags:
  - profile
  - ssh-agent

- name: Copy the configuration file to '/root/.profile'.
  become: true
  copy:
    src: .profile
    dest: /root/.profile
    group: root
    owner: root
    mode: 0644
  tags:
  - profile
  - ssh-agent
