- name: Copy the configuration file to '~/.dircolors'.
  copy:
    src: .dircolors
    dest: ~/.dircolors
    mode: 0644
  tags:
  - dircolors

- name: Copy the configuration file to '/root/.dircolors'.
  become: true
  copy:
    src: .dircolors
    dest: /root/.dircolors
    group: root
    owner: root
    mode: 0644
  tags:
  - dircolors
