- name: Copy the configuration file to '~/.bashrc'.
  copy:
    src: .bashrc
    dest: ~/.bashrc
    mode: 0644
  tags:
  - bash

- name: Copy the configuration file to '/root/.bashrc''.
  become: true
  copy:
    src: .bashrc
    dest: /root/.bashrc
    group: root
    owner: root
    mode: 0644
  tags:
  - bash
