#
# We need to configure the Docker daemon specifically
# if we are running it behind a proxy server.
#
# https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
#
- name: Create the systemd drop-in directory '/etc/systemd/system/docker.service.d'.
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    group: root
    owner: root
    mode: 0755

- name: Copy the http-proxy.conf file to '/etc/systemd/system/docker.service.d/http-proxy.conf'.
  become: yes
  copy:
    src: http-proxy.conf
    group: root
    owner: root
    mode: 0777
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify:
    - Restart the docker daemon.

- name: Add 'Environment="HTTP_PROXY=[...]"' in section '[Service]'.
  become: yes
  lineinfile:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    line: "Environment=\"HTTP_PROXY={{ ansible_env.http_proxy }}\""
    state: present
  when: (ansible_env.http_proxy is defined) and (ansible_env.http_proxy|length > 0)
  notify:
    - Restart the docker daemon.

- name: Add 'Environment="HTTPS_PROXY=[...]"' in section '[Service]'.
  become: yes
  lineinfile:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    line: "Environment=\"HTTPS_PROXY={{ ansible_env.https_proxy }}\""
    state: present
  when: (ansible_env.https_proxy is defined) and (ansible_env.https_proxy|length > 0)
  notify:
    - Restart the docker daemon.

- name: Add 'Environment="NO_PROXY=[...]"' in section '[Service]'.
  become: yes
  lineinfile:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    line: "Environment=\"NO_PROXY={{ ansible_env.no_proxy }}\""
    state: present
  when: (ansible_env.no_proxy is defined) and (ansible_env.no_proxy|length > 0)
  notify:
    - Restart the docker daemon.
