- name: Install a specific version of the Docker CE packages.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  loop:
    - containerd.io=1.6.6-1
    - docker-ce=5:20.10.17~3-0~debian-bullseye
    - docker-ce-cli=5:20.10.17~3-0~debian-bullseye
